XRT-1188 branch
IOTechSystems/xrt-examples pull request #100
Opened 2022-02-11 11:47 UTC by Tylerg2471

2022-02-14 10:20 UTC, dpazj requested changes
One small comment. Can you also update the title of the PR to describe what is going in?

2022-02-14 10:20 UTC, dpazj commented on DeviceServices/s7/deployment/config/logger.json
> +  "Level":"Debug"
This should be "Level": "Warn"

2022-02-15 08:56 UTC, Tylerg2471 commented on DeviceServices/s7/deployment/config/logger.json
> +  "Level":"Debug"
Fixed now

2022-02-15 09:54 UTC, dpazj approved these changes
LGTM

2022-02-15 09:54 UTC, merged