XRT-1696: Tidy up azure configs & docs
IOTechSystems/xrt-examples pull request #165
Opened 2022-08-04 11:00 UTC by amaan-akram

will update modbus example and docs under https://iotechsys.atlassian.net/jira/software/projects/XRT/boards/65?assignee=60a22dc797f3d4007011cf77&selectedIssue=XRT-1679

2022-08-04 14:14 UTC, BinduRao2018 requested changes
Have left few inline comments

2022-08-04 14:14 UTC, BinduRao2018 commented on AzureSphere/docs/ethernetip-example.md
>  "properties" / "desired" / "Components" / "azure". This is can be
typo: This is can be

2022-08-04 14:14 UTC, BinduRao2018 commented on AzureSphere/docs/ubuntu-installation.md
>  curl -L -O https://iotech.jfrog.io/ui/native/windows-release/azuresphere-12/iotech-xrt-dev-azsphere12-2.0-latest.zip
Why do we suffix the image with 'latest'?

2022-08-04 14:14 UTC, BinduRao2018 commented on AzureSphere/docs/windows-installation.md
> +When updating the xrt packages with a newer version, it is recommended that you reinstall the azure sphere SDK to ensure we have a clean sysroots directory. After this the same steps can be followed
Not clear. Are we saying about the update or fresh install?

2022-08-04 14:25 UTC, amaan-akram commented on AzureSphere/docs/bacnet-example.md
> +An example profile is already included on the [Example desired-bacnet.json](../twin/desired-bacnet.json)
First I point to an example bacnet profile that is normally used in XRT, this gives the user a clean example of how to create a profile relating it back to core XRT.

Then I mention that the azure examples already have an example profile so there is no need to add a new one if wanting to run this specific example, however for refrence I think it's still good to point to the main bacnet configurations.

Thoughts on this?

2022-08-04 14:28 UTC, BinduRao2018 commented on AzureSphere/docs/bacnet-example.md
> +An example profile is already included on the [Example desired-bacnet.json](../twin/desired-bacnet.json)
Got it. There is no harm in adding additional info. Ignore my comment.

2022-08-04 14:40 UTC, amaan-akram commented on AzureSphere/docs/ubuntu-installation.md
>  curl -L -O https://iotech.jfrog.io/ui/native/windows-release/azuresphere-12/iotech-xrt-dev-azsphere12-2.0-latest.zip
Not sure, should probably follow the same versioning style as all our other packages

2022-08-04 14:49 UTC, amaan-akram commented on AzureSphere/docs/windows-installation.md
> +When updating the xrt packages with a newer version, it is recommended that you reinstall the azure sphere SDK to ensure we have a clean sysroots directory. After this the same steps can be followed
If the user already had an installation of XRT for Azure and wish to update to a newer release.

added some more points in text for clarification

2022-08-04 14:52 UTC, amaan-akram commented on AzureSphere/docs/ethernetip-example.md
> +The Device profile contains a config of different deviceResources
I will look into cleaning up repeated sections, may need to tidy up and restructure further

2022-08-04 16:07 UTC, BinduRao2018 commented on AzureSphere/docs/ubuntu-installation.md
>  curl -L -O https://iotech.jfrog.io/ui/native/windows-release/azuresphere-12/iotech-xrt-dev-azsphere12-2.0-latest.zip
Could change in 2.1 after discussion. For now, can leave it as is.

2022-08-05 10:26 UTC, BinduRao2018 requested changes
2 comments in-line

2022-08-05 10:26 UTC, BinduRao2018 commented on AzureSphere/docs/ethernetip-example.md
> -The Device profile contains a config of different deviceResources that can be sent or received from the Azure IoT Hub.
Info on Device profile should be the first sentence under 'Device Profile'

2022-08-05 10:26 UTC, BinduRao2018 commented on AzureSphere/docs/windows-installation.md
> +If an outdated version of XRT for azure is already installed and you
Above command references azsphere11

2022-08-08 11:46 UTC, merged