Xrt 1679 branch
IOTechSystems/xrt-examples pull request #168
Opened 2022-08-17 15:00 UTC by amaan-akram

Will create PR for 2.1 once reviewed

2022-08-18 15:31 UTC, BinduRao2018 requested changes
Minor comments in-line

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/README.md
> +For first time configuration setup, run the setup_configs.sh script within the AazureSphere Directory:
Typo: AzureSphere, Also should be 'Azure Sphere' and not  AzureSphere wherever referenced

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/README.md
> +* [Virutal Device](docs/virtual-example.md)
Typo: Virtual

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/docs/ethernetip-example.md
> +To get started with the BACnet example we have to first setup all
Typo: Should be Ethernet/IP

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/docs/modbus-example.md
> +values read from the choosen Modbus Device are then sent to its
Typo: should be chosen Also the statement starting from 'Values read from the chosen Modbus Device..' should appear on a new line. Check formating

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/docs/modbus-example.md
> +There is also an in house [dockerised simulator](#using-the-inhouse-dockerised-simulator-with-the-example) available which can be
could say dockerised simulator [Modbus-Sim] for clarity

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/docs/modbus-example.md
> +and can be ran from either the host PC or a sperate host and can
typo: separate

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/docs/modbus-example.md
> +docker run --rm --name modbus-sim iotechsys/modbus-sim
Since it is a docker container, this doesn't require any installation. Is the version number of the image not mandatory not required?

2022-08-18 15:31 UTC, BinduRao2018 commented on AzureSphere/docs/ubuntu-build.md
> +XRT for AzureSphere can be build and run on Visual Studio Code, to see how you can build on vscode see [Building on Visual Studio Code](./vscode-build.md).
should be built

2022-08-19 12:11 UTC, BinduRao2018 commented
@amaan-akram, Is this ready for re-review? Could you update the status once the review comments are addressed?

2022-08-19 13:23 UTC, BinduRao2018 commented on AzureSphere/docs/modbus-example.md
> +values read from the choosen Modbus Device are then sent to its
Closing bracket missing for Modbus TCP/IP Device (Damocles2 Mini)

2022-08-19 13:37 UTC, BinduRao2018 commented on AzureSphere/docs/modbus-example.md
> +docker run --rm --name modbus-sim iotechsys/modbus-sim
Better to drop patch version: should be modbus-sim:1.0

2022-08-19 13:40 UTC, amaan-akram commented on AzureSphere/docs/modbus-example.md
> +docker run --rm --name modbus-sim iotechsys/modbus-sim
Fixed

2022-08-19 13:40 UTC, amaan-akram commented on AzureSphere/docs/modbus-example.md
> +values read from the choosen Modbus Device are then sent to its
done

2022-08-19 13:42 UTC, BinduRao2018 approved these changes
LGTM

2022-08-19 13:42 UTC, merged