XRT-1949: Added Zigbee Example
IOTechSystems/xrt-examples pull request #191
Opened 2022-11-17 13:51 UTC by AIM289

2022-11-17 14:57 UTC, FraserG01 requested changes
- Require getting started sub-section on the device that is being used
- Require getting started sub-section for running zigbee2mqtt, also provide a start_zigbee2mqtt.sh and stop_zigbee2mqtt.sh commands
-

2022-11-22 14:07 UTC, AIM289 commented
> * Require getting started sub-section on the device that is being used
> * Require getting started sub-section for running zigbee2mqtt, also provide a start_zigbee2mqtt.sh and stop_zigbee2mqtt.sh commands
> * Also require extra section on readme on protocol specific commands, see: https://github.com/IOTechSystems/xrt-examples/tree/XRT-1949-branch/DeviceServices/opc-ua#subscriptions and https://github.com/IOTechSystems/xrt-examples/tree/XRT-1949-branch/DeviceServices/bacnet-ip#change-of-value-subscriptions for examples

Added these sections as well as z2mqtt start/stop scripts

2022-11-22 14:54 UTC, FraserG01 requested changes

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/commands/add_polled_schedule.sh
> +mosquitto_pub -t xrt/devices/zigbee/request -m \
file should be named add_schedule as the docs refer to the command as that

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/commands/remove_polled_schedule.sh
> +mosquitto_pub -t xrt/devices/zigbee/request -m \
file should be named remove_schedule as the docs refer to the command as that

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/deployment/config/main.json
> +  "logger_debug":"IOT::Logger",
dont need logger_debug

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/deployment/config/logger_debug.json
> +{
done need logger_debug

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/deployment/state/schedules.json
> +{"apiVersion":"v2","schedules":[]}
there should be an initial schedule

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/README.md
> +Unlike many of the examples for the other Device Services, there is no readily available Zigbee device simulator. Therefore, this example is instead based off two real world devices which are require
worth having a note saying the friendly names would need to be updated for this example to actually work?

Could also put a note that if using different devices they could just clear devices.json and schedules.json and run discovery with AutoRegister turned to true?

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/commands/start_zigbee2mqtt.sh
> +read -p "Input Zigbee adapter location:" adapterlocation
Arguments would be better to use as can be avoids runtime user input

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/README.md
> +. ./commands/start_zigbee2mqtt.sh
is there a reason this shell script needs the first dot

2022-11-22 14:54 UTC, FraserG01 commented on DeviceServices/zigbee/README.md
> +. ./commands/stop_zigbee2mqtt.sh
is there a reason this shell script needs the first dot

2022-11-22 14:56 UTC, FraserG01 commented on DeviceServices/zigbee/commands/start_zigbee2mqtt.sh
> +docker run \
can you add --rm to this run command

2022-11-22 14:56 UTC, FraserG01 commented on DeviceServices/zigbee/commands/stop_zigbee2mqtt.sh
> +docker rm zigbee2mqtt
with --rm added to the docker run, the image shouldnt need to be removed

2022-11-22 15:38 UTC, AIM289 commented on DeviceServices/zigbee/commands/add_polled_schedule.sh
> +mosquitto_pub -t xrt/devices/zigbee/request -m \
renamed

2022-11-22 15:39 UTC, AIM289 commented on DeviceServices/zigbee/deployment/config/main.json
> +  "logger_debug":"IOT::Logger",
removed

2022-11-22 15:39 UTC, AIM289 commented on DeviceServices/zigbee/deployment/config/logger_debug.json
> +{
removed

2022-11-22 15:39 UTC, AIM289 commented on DeviceServices/zigbee/deployment/state/schedules.json
> +{"apiVersion":"v2","schedules":[]}
added

2022-11-22 15:44 UTC, AIM289 commented on DeviceServices/zigbee/README.md
> +Unlike many of the examples for the other Device Services, there is no readily available Zigbee device simulator. Therefore, this example is instead based off two real world devices which are require
Added notes

2022-11-22 15:44 UTC, AIM289 commented on DeviceServices/zigbee/commands/start_zigbee2mqtt.sh
> +read -p "Input Zigbee adapter location:" adapterlocation
switched to use args

2022-11-22 15:44 UTC, AIM289 commented on DeviceServices/zigbee/README.md
> +. ./commands/start_zigbee2mqtt.sh
removed dot

2022-11-22 15:44 UTC, AIM289 commented on DeviceServices/zigbee/README.md
> +. ./commands/stop_zigbee2mqtt.sh
removed dot

2022-11-22 15:44 UTC, AIM289 commented on DeviceServices/zigbee/commands/start_zigbee2mqtt.sh
> +docker run \
added

2022-11-22 15:44 UTC, AIM289 commented on DeviceServices/zigbee/commands/stop_zigbee2mqtt.sh
> +docker rm zigbee2mqtt
removed

2022-11-22 15:46 UTC, FraserG01 commented on DeviceServices/zigbee/README.md
> +./commands/start_zigbee2mqtt.sh arg1 arg2 arg3
not better having labelled arguments?

--adapter=<location>

etc

2022-11-23 09:49 UTC, AIM289 commented on DeviceServices/zigbee/README.md
> +./commands/start_zigbee2mqtt.sh arg1 arg2 arg3
Now uses labelled args

2022-11-23 10:44 UTC, FraserG01 requested changes

2022-11-23 10:44 UTC, FraserG01 commented on DeviceServices/zigbee/README.md
> +- MQTT_NETWORK: Network of MQTT broker
would it not be better to indicate that is is the the docker network you are choosing (host or the name of a docker network its to run on)

2022-11-23 10:44 UTC, FraserG01 commented on DeviceServices/zigbee/README.md
> +Using the following values:
Worth having an example usage of the full command with filled in arguments?

2022-11-23 11:11 UTC, AIM289 commented on DeviceServices/zigbee/README.md
> +- MQTT_NETWORK: Network of MQTT broker
Changed

2022-11-23 11:11 UTC, AIM289 commented on DeviceServices/zigbee/README.md
> +Using the following values:
Added example

2022-11-23 11:36 UTC, FraserG01 approved these changes
LGTM

2022-11-23 11:36 UTC, merged