XRT-2128 Fixed MakeFile dirs, app-component incorrect pointer type, a…
IOTechSystems/xrt-examples pull request #206
Opened 2023-02-22 15:28 UTC by luke-shields

- [x]     Versions of dev packages in prerequisites are incorrect 
- [x]     Folder structure of files is also incorrect
- [x]     Folder structure in Make file is incorrect
- [x]     Warning raised when compiling app component
- [ ]     Segfault when closing XRT process with ApplicationComponent loaded - Still pending
- [ ]     Ticket should also be raised to output error if XRT called with incorrect config path specified - Still pending

2023-02-24 11:45 UTC, luke-shields commented
@dpazj  PR raised

2023-02-24 12:29 UTC, dpazj commented on ApplicationComponent/README.md
> +This example uses the [Virtual Device Service](https://docs.iotechsys.com/edge-xrt20/device-service-components/virtual-device-service-component.html) to schedule regular publishing of a store value (
The data is published under **the** `"/xrt/devices/virtual/telemetry"` topic on the Xrt bus

2023-02-24 13:13 UTC, dpazj requested changes
- Can you remove the drawio note in the Application_Component.drawio.svg diagram.

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +The aim of this example is to demonstrate how a custom component (app_component) can be built and loaded into XRT and subsequently used alongside other components.
XRT should be Xrt

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +This example uses the [Virtual Device Service](https://docs.iotechsys.com/edge-xrt20/device-service-components/virtual-device-service-component.html) to schedule regular publishing of a store value (
I would mention about there being two devices, each with one schedule that reads the "StoreInt32Value" resource

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +A [Lua component](https://docs.iotechsys.com/edge-xrt20/transform-components/lua-transform-component.html) is attached which subscribes to this topic and transforms the data (multiplies each data val
```suggestion
A [Lua component](https://docs.iotechsys.com/edge-xrt20/transform-components/lua-transform-component.html) is attached which subscribes to the telemetry topic and transforms the data (multiplies each data value by 10) before re-publishing the new values on the `"/xrt/lua/transformed_data"` topic. There is also a custom application component which subscribes to the `"/xrt/lua/transformed_data"` topic, adds the two values together and increments an overall counter before re-publishing the final result back to the XRT bus on the `"/xrt/app_component/result"` topic. Finally, an MQTT bridge component is attached which subscribes to the `"/xrt/app_component/result"` topic on the Xrt bus and publishes any message received on a MQTT topic `"/xrt/app_component/result"`.  
```

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +Below an illustration of the scenario described above:
Below is an illustration of the scenario described above:

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +If they are not please install with `sudo apt install`
I realise we can actually remove this section - removes the hassle of having to maintain and update versions

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +XRT dev must be installed. Verify with the command:
The Xrt development package

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +XRT dev must be installed. Verify with the command:
Can remove the "Verify with the command" bit

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +Environment variables must be set as usual with the command:
Environment variables can be set with the command:

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +There are a couple of function pointers to be implemented in order to support the state transitions of the application component that has been created in this example in the C language.
```suggestion
There are a couple of function that have been implemented in order to support the state transitions of the application component that has been created in this example in the C language.
```

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +### alloc
Probably worth updating these headers to correspond to the functions in the source, e.g app_component_alloc

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/README.md
> +Provides the possibility to configure and access each individual field that has been set in the [`app_component.json`](../deployment/config/app_component.json) file.
```suggestion
Provides the possibility to configure and access each field that has been set in the [`app_component.json`](../deployment/config/app_component.json) configuration file.
```

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/app-component/Makefile
> +	rm libapp-component.so
add end of file new line

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/app-component/app-component.c
> +static void app_component_add_callback (const iot_data_t * data, void * self, const char * match)
Not your fault but I realise this function does not do what it is supposed to. It will never actually add the values of both devices.

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/deployment/config/app_component.json
>  }
add EOF new line

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/deployment/config/mqtt_bridge.json
> +}
EOF new line

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/deployment/config/multiply.lua
> +CHANGE = 10
As discussed this should be updated for correctness

2023-02-24 13:13 UTC, dpazj commented on ApplicationComponent/deployment/profiles/profiles.json
> +["device-virtual1","device-virtual2"]
Add end of file new line

2023-02-24 14:43 UTC, luke-shields commented
@dpazj Made review changes

2023-02-27 08:46 UTC, dpazj requested changes
A few minor changes required, other than that looks good.

2023-02-27 08:46 UTC, dpazj commented on ApplicationComponent/Application_Component.drawio.svg
> +    <defs/>
On MQTT Bridge section: 
pub to /xrt/app_component_result -> pub to /xrt/app_component/result

2023-02-27 08:46 UTC, dpazj commented on ApplicationComponent/README.md
> +Finally an MQTT bridge component subscribes to the `"/xrt/app_component/result"` topic on the Xrt bus and re-publishes any message received on a MQTT topic `"/xrt/app_component/result"`.
Missing comma after finally

2023-02-27 08:46 UTC, dpazj commented on ApplicationComponent/README.md
> +There are a couple of function pointers that have been implemented in order to support the state transitions of the application component that has been created in this example in the C language.
remove "pointers"

2023-02-27 08:46 UTC, dpazj commented on ApplicationComponent/app-component/app-component.c
> +#define DEVICE2_NAME "\"Random-Device2\""
I think these can just be "Random-Device1" without the escaped quotations

2023-02-27 09:43 UTC, luke-shields commented on ApplicationComponent/app-component/app-component.c
> +#define DEVICE2_NAME "\"Random-Device2\""
Component does not correctly detect name without escaped quotations

2023-02-27 10:50 UTC, luke-shields commented
@BinduRao2018

2023-02-28 15:34 UTC, dpazj reviewed
Few final comments. I have updated the wording of some of the description of the ApplicationComponent/README.md

2023-02-28 15:34 UTC, dpazj commented on ApplicationComponent/README.md
> +Finally, an MQTT bridge component subscribes to the `"/xrt/app_component/result"` topic on the Xrt bus and re-publishes any message received on a MQTT topic `"/xrt/app_component/result"`.
```suggestion
Finally, an MQTT bridge component, acting as an MQTT exporter, subscribes to the `"/xrt/app_component/result"` topic and re-publishes any message received so that the data can be accessed by any client subscribed to that MQTT topic on the broker.
```

2023-02-28 15:34 UTC, dpazj commented on ApplicationComponent/Makefile
> +XRT_DIR=/opt/iotech/xrt/2.1
Was it possible to have IOT_DIR and XRT_DIR set in "set_env_vars.sh" and used them in this Makefile?

2023-02-28 15:34 UTC, dpazj commented on ApplicationComponent/README.md
> +Included in this example are two Virtual Device Services, a Lua Transform Component, a custom component and an MQTT bridge component.
```suggestion
This example consists of a Virtual Device Service, a Lua Transform component, an MQTT bridge component and the custom 'app component'. 
```

2023-02-28 15:34 UTC, dpazj commented on ApplicationComponent/README.md
> +The two [Virtual Device Service](https://docs.iotechsys.com/edge-xrt20/device-service-components/virtual-device-service-component.html) are both setup with a scheduler. This scheduler reads from a re
```suggestion
The [Virtual Device Service](https://docs.iotechsys.com/edge-xrt20/device-service-components/virtual-device-service-component.html) is used to generate random data. It is set up with two devices, each with a schedule that reads a resource whose value is randomly generated. The values of these resources are periodically published under the `"/xrt/devices/virtual/telemetry"` topic on the Xrt bus.
```

2023-02-28 15:34 UTC, dpazj commented on ApplicationComponent/README.md
> +```
This will need update as we removed the app-component folder

2023-02-28 15:34 UTC, dpazj commented on ApplicationComponent/app-component.c
> + * IoTech Ltd
Need to apply formatting

2023-03-01 09:20 UTC, dpazj requested changes

2023-03-01 09:20 UTC, dpazj commented on ApplicationComponent/app-component.c
> +      NULL};
Seems like there is some weird formatting here, just add a new line after NULL

2023-03-01 09:20 UTC, dpazj commented on CommonCommands/set_env_vars.sh
> +export XRT_DIR=/opt/iotech/xrt/2.1
EOF newline

2023-03-01 10:24 UTC, dpazj approved these changes
LGTM

2023-03-01 10:26 UTC, dpazj commented
@BinduRao2018 The read me has been updated based on our discussion - can you take a look?

2023-03-01 12:53 UTC, BinduRao2018 reviewed
Comments in-line.
General comment: 
- It would be better to merge this update to the v2.2-branch as 2.1 is in maintenance.
- Links are pointing to 2.0 docs, leave a ticket to update to 2.2
- In the diagram, Random-Device1 & 2 should indicate data being published (replace the bi-directional arrow with a uni directional arrow to indicate data flowing to the bus)

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/README.md
> +The [Virtual Device Service](https://docs.iotechsys.com/edge-xrt20/device-service-components/virtual-device-service-component.html) is used to generate random data. It is set up with two devices, eac
should map to 2.1 branch ie edge-xrt21

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/README.md
> +. ../CommonCommands/set_env_vars.sh
Why is there a folder? Can't this script directly be at the top level?

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/README.md
> +XRT dev must be installed.
- PATH & LD_LIBRARY_PATH must be set
- XRT_LICENSE_FILE should be set

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/README.md
> +cd ApplicationComponent
Already in the ApplicationComponent directory. So just executing xrt should be ok

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/README.md
> +to start the Xrt instance with the example application component.
Is this part of the Note? check indentation

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/app-component.c
> + * Copyright (c) 2021
Change the copyright to 2023

2023-03-01 12:53 UTC, BinduRao2018 commented on ApplicationComponent/deployment/state/devices.json
> +      "name": "Random-Device1",
For simplicity, can't the device name and profile name be the same?

2023-03-01 14:18 UTC, luke-shields commented on ApplicationComponent/README.md
> +cd ApplicationComponent
I think leaving this in makes it clear which directory the command must be run in?

2023-03-01 14:19 UTC, luke-shields commented on ApplicationComponent/deployment/state/devices.json
> +      "name": "Random-Device1",
I think the difference makes clear that these are not required to be the same, might be my lack of background in this area but I think if I aw that these were the same I might have assumed that this was a requirement.

2023-03-01 14:20 UTC, luke-shields commented
@BinduRao2018 I have made most the changes just wanted to confirm a couple of them. I am also going to raise a ticket for further organisation of the examples as additional aspects of them could be made more clear.

2023-03-01 14:47 UTC, BinduRao2018 commented on ApplicationComponent/README.md
> +cd ApplicationComponent
previous 'make' assume initial settings

2023-03-01 14:47 UTC, BinduRao2018 commented on ApplicationComponent/deployment/state/devices.json
> +      "name": "Random-Device1",
agree! No need to change

2023-03-02 09:48 UTC, luke-shields commented
@dpazj @BinduRao2018 All changes made and pushed now for confirmation. Once this is merged I will open another PR for 2.2 and update the documentation links accordingly

2023-03-02 09:57 UTC, dpazj commented
> @dpazj @BinduRao2018 All changes made and pushed now for confirmation. Once this is merged I will open another PR for 2.2 and update the documentation links accordingly

@BinduRao2018 Am I right in thinking we only want these changes to go into v2.2-branch? In this case @luke-shields we can just close this PR and create a new PR to merge changes only into v2.2

2023-03-02 11:20 UTC, BinduRao2018 commented
@luke-shields executing application component test results in a crash
'free(): double free detected in tcache 2
Aborted (core dumped)'

2023-03-03 10:32 UTC, closed without merging