XRT-2209 feat(opc-ua-server): Added Modbus tcp, bacnet ip and virtual services to opv-ua server examples
IOTechSystems/xrt-examples pull request #213
Opened 2023-03-31 15:41 UTC by Tylerg2471

2023-04-12 13:17 UTC, BinduRao2018 requested changes
Minor comments in-line

2023-04-12 13:17 UTC, BinduRao2018 commented on Servers/opc-ua/basic/README.md
> +export MODBUS_SIM_ADDRESS=$<ip_of_sim>
use the same convention : should be export MODBUS_SIM_ADDRESS=<ip_of_sim>  (without $)

2023-04-12 13:17 UTC, BinduRao2018 commented on set_env_vars.sh
>  export XRT_DIR=/opt/iotech/xrt/2.1
XRT_DIR - change it to 2.2

2023-04-13 10:47 UTC, Tylerg2471 commented on Servers/opc-ua/basic/README.md
> +export MODBUS_SIM_ADDRESS=$<ip_of_sim>
Fixed

2023-04-13 10:47 UTC, Tylerg2471 commented on set_env_vars.sh
>  export XRT_DIR=/opt/iotech/xrt/2.1
Updated

2023-04-13 11:12 UTC, BinduRao2018 approved these changes
LGTM

2023-04-13 11:12 UTC, merged