XRT-2324: Added file device service configs
IOTechSystems/xrt-examples pull request #228
Opened 2023-06-22 10:19 UTC by Tylerg2471

2023-06-30 15:57 UTC, BinduRao2018 requested changes

2023-06-30 15:57 UTC, BinduRao2018 commented on DeviceServices/file/deployment/config/sparkplug.json
> +    "AppStateWait": [ "${SPARKPLUG_APPS}" ],
@Tylerg2471, Setting the AppStateWait to sparkplug_apps results in the xrt waiting for the apps to start.

2023-06-30 15:57 UTC, BinduRao2018 commented on DeviceServices/file/README.md
> +To set the Directory path for the example device run the following, replacing `directory-path` with the required path:
An example would be better. Is it possible to set the path to /etc or /usr?

2023-06-30 15:57 UTC, BinduRao2018 commented on DeviceServices/file/README.md
> +For basic device service operations see the [Basic Operations Walkthrough](../interactive-walkthrough/basic-operations.md) guide.
General instructions should include verifying using spb_client (with and without spb)

2023-06-30 15:57 UTC, BinduRao2018 commented on DeviceServices/file/deployment/config/8-sparkplug.json
> +{"AppStateWait":[],"Bus":"6-bus","Factory":"xrt_sparkplug_factory","Group":"iotech","Library":"libxrt-sparkplug.so","Logger":"2-logger","NodeId":"xrt","bdSeq":15}
sparkplug.json - update to use env variable SPARKPLUG_PROTO, SPARKPLUG_NODE

2023-06-30 15:57 UTC, BinduRao2018 commented on set_env_vars.sh
> +export XRT_FILE_PROFILE_DIR=../../../DeviceServices/file/deployment/profiles
XRT_FILE_PROFILE_DIR is not required

2023-07-03 08:23 UTC, Tylerg2471 commented on DeviceServices/file/deployment/config/sparkplug.json
> +    "AppStateWait": [ "${SPARKPLUG_APPS}" ],
Updated

2023-07-03 08:24 UTC, Tylerg2471 commented on DeviceServices/file/deployment/config/8-sparkplug.json
> +{"AppStateWait":[],"Bus":"6-bus","Factory":"xrt_sparkplug_factory","Group":"iotech","Library":"libxrt-sparkplug.so","Logger":"2-logger","NodeId":"xrt","bdSeq":15}
Updated to use SPARKPLUG_GROUP and SPARKPLUG_NODE. I've not seen SPARKPLUG_PROTO used in any of the templates.

2023-07-03 08:24 UTC, Tylerg2471 commented on set_env_vars.sh
> +export XRT_FILE_PROFILE_DIR=../../../DeviceServices/file/deployment/profiles
Updated

2023-07-03 15:12 UTC, BinduRao2018 commented on DeviceServices/file/README.md
> +For basic device service operations see the [Basic Operations Walkthrough](../interactive-walkthrough/basic-operations.md) guide.
Discussed. Will be updated when the branch is stable with spb.

2023-07-03 15:22 UTC, BinduRao2018 approved these changes
LGTM

2023-07-03 15:22 UTC, merged