XRT-2639: Added OPC-UA Alarm configuration
IOTechSystems/xrt-examples pull request #251
Opened 2023-11-17 17:56 UTC by BinduRao2018

2023-11-20 15:15 UTC, dpazj requested changes
We refer to this example as "alarms", however I think it might be best to make it clear that this an example for the `events_registration component` - which allows you to monitor events/conditions/alarms on an opc-ua server.

2023-11-20 15:15 UTC, dpazj commented on DeviceServices/opc-ua/commands/start_device_sim.sh
> +docker run --rm -d --network=host --name opc-ua-sim $OPC_UA_SIM --discovery-url=opc.tcp://$(hostname):4840
I think this should be reverted as the other examples still require the simulation script to be run?

2023-11-20 15:15 UTC, dpazj commented on DeviceServices/opc-ua/alarms/README.md
> +_To know more on the event management and event format, see [OPC-UA Event Registration Component](https://docs.iotechsys.com/edge-xrt22/extension-components/opc-ua-event-registration-component.html).
```suggestion
_For more information about event management, see [OPC-UA Event Registration Component](https://docs.iotechsys.com/edge-xrt22/extension-components/opc-ua-event-registration-component.html)._ 
```

2023-11-20 15:15 UTC, dpazj commented on DeviceServices/opc-ua/alarms/README.md
> +Below command will setup an alarm to a monitored resource.
```suggestion
The below command will register the monitoring of events on a resource. 
```

2023-11-20 15:15 UTC, dpazj commented on DeviceServices/opc-ua/alarms/README.md
> +
Add some more info about why this triggers the alarm - 
"In this example, the condition is configured to produce an event when it's severity changes. This command will change the severity of the condition and will trigger an event"

2023-11-20 15:15 UTC, dpazj commented on DeviceServices/opc-ua/README.md
> +A separate example configuration [alarms](./alarms) has been added to demonstrate OPC-UA alarms.
Perhaps we can reword this to: 
A separate example configuration [alarms](./alarms) has been added to demonstrate the OPC-UA device service events registration component.

2023-11-22 14:18 UTC, BinduRao2018 commented on DeviceServices/opc-ua/commands/start_device_sim.sh
> +docker run --rm -d --network=host --name opc-ua-sim $OPC_UA_SIM --discovery-url=opc.tcp://$(hostname):4840
Updated

2023-11-22 14:18 UTC, BinduRao2018 commented on DeviceServices/opc-ua/alarms/README.md
> +_To know more on the event management and event format, see [OPC-UA Event Registration Component](https://docs.iotechsys.com/edge-xrt22/extension-components/opc-ua-event-registration-component.html).
Addressed.

2023-11-22 14:19 UTC, BinduRao2018 commented on DeviceServices/opc-ua/alarms/README.md
> +Below command will setup an alarm to a monitored resource.
Addressed.

2023-11-22 14:19 UTC, BinduRao2018 commented on DeviceServices/opc-ua/alarms/README.md
> +
Updated.

2023-11-22 14:20 UTC, BinduRao2018 commented on DeviceServices/opc-ua/README.md
> +A separate example configuration [alarms](./alarms) has been added to demonstrate OPC-UA alarms.
Updated. The new example config is under event-registration instead of Alarms as suggested above.

2023-11-27 09:41 UTC, dpazj approved these changes
LGTM

2023-11-27 11:32 UTC, merged