XRT-2611: Sunspec 3.0 example
IOTechSystems/xrt-examples pull request #256
Opened 2023-12-13 01:18 UTC by Jwcode-uk

2024-01-04 13:38 UTC, dpazj requested changes
Can you replace references to OPC-UA with OPC UA

2024-01-04 13:38 UTC, dpazj commented on DeviceServices/virtual/commands/get_request.sh
I dont think you meant to update this?

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/Explanation.md
> +This demonstration showcases the integration and interaction between Edge Connect Modbus Device Services and an OPC-UA server using MQTT. The focus is on monitoring and manipulating temperature data
```suggestion
This demonstration showcases the integration and interaction between Edge Connect Modbus Device Services and an OPC-UA server using Sparkplug over MQTT. The focus is on monitoring and manipulating temperature data from battery cells. Although a simple demo running on one machine, this is designed to show how you can use XRT across multiple hardware nodes, for example a gateway running a opc-ua server with multiple hardware nodes running device services sending data.
```

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/Explanation.md
> + -   Edge Connect Modbus Device Service: Responsible for    reading device data according to a specified schedule.
extra spacing after 'for'

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> +[Sunspec model](https://sunspec.org/wp-content/uploads/2015/06/SunSpec-Information-Models-12041.pdf) that has been converted into an Nodeset.
```suggestion
[Sunspec model](https://sunspec.org/wp-content/uploads/2015/06/SunSpec-Information-Models-12041.pdf) that has been converted to an OPC UA Nodeset.
```

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> +
extra whitespace

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> +### Prerequisites
leave a newline after a title - take a look at markdownlint vs code extension

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> +This section outlines the setup process for the IOTech OPC-UA browser. If you opt to use a different OPC-UA browser, please refer to the corresponding instructions specific to that browser.
add a new line before a title

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> +    You should be able to see the nodeset model loaded in under:
```suggestion
You should be able to see the model data defined by `opc-ua/deployment/models/Sunspec_Model805.json` loaded in under:
```

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> +   modbus device -> Sparkplug -> xrt -> modbus-device1 -> cell_1_tmp
Should this just be
```suggestion
Sparkplug -> xrt -> modbus-device1 -> cell_1_tmp
```

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/images/Deployment.png
Can we remove then "Made with Whimsical" watermark?

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/modbus-tcp/sim_files/MyScript
Should this be a .py file extension?

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/opc-ua/deployment/config/logger.json
> +  "Level": "trace"
Set to "info" for examples

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/opc-ua/deployment/config/serverlogger.json
> +  "Level": "trace"
Set to info for examples

2024-01-04 13:38 UTC, dpazj commented on Servers/opc-ua/federated/scripts/add_device.sh
We can get rid of all the escapes by just wrapping the json message in ' ': 
```
#!/bin/sh

mosquitto_pub -t spBv1.0/iotech/REQUEST/xrt/modbus_tcp -m \
'{
  "client": "example",
  "request_id":"1010",
  "op": "device:add",
  }
}'
```

2024-01-10 05:06 UTC, dpazj commented on DeviceServices/virtual/commands/get_request.sh
Why has this been changed from the original?

2024-01-10 05:06 UTC, dpazj commented on Servers/opc-ua/federated/README.md
> + Specifically, it utilizes a modified version of Sunspec's [Model805](https://github.com/sunspec/models/blob/master/json/model_805.json) to create an instance of a Lithium-ion module.
"it utilizes a modified version..."? This implies that we have modifed the original json model, which I believe is not the case?

2024-01-10 07:43 UTC, Jwcode-uk commented on Servers/opc-ua/federated/README.md
> + Specifically, it utilizes a modified version of Sunspec's [Model805](https://github.com/sunspec/models/blob/master/json/model_805.json) to create an instance of a Lithium-ion module.
changed this to 'it uses Sunspec'

2024-01-10 08:05 UTC, Jwcode-uk commented on DeviceServices/virtual/commands/get_request.sh
reverted change

2024-01-10 08:18 UTC, dpazj approved these changes
LGTM

2024-01-10 13:24 UTC, merged