XRT-2585: Add Canbus examples
IOTechSystems/xrt-examples pull request #257
Opened 2024-01-18 15:21 UTC by Tylerg2471

2024-01-19 17:35 UTC, BinduRao2018 reviewed
in-line comments

2024-01-19 17:35 UTC, BinduRao2018 commented on DeviceServices/canbus/deployment/config/pool.json
> +  "Threads": 8
Any reason to set the threads to 8?

2024-01-19 17:35 UTC, BinduRao2018 commented on DeviceServices/canbus/commands/add_string_device.sh
> +    "profileName": "canbus-profile-strings",
trying to add a device without an existing profile - canbus-profile-strings. Is this ok?

2024-01-22 15:53 UTC, Tylerg2471 commented on DeviceServices/canbus/deployment/config/pool.json
> +  "Threads": 8
Updated to be the default by removing the Threads parameter

2024-01-22 15:54 UTC, Tylerg2471 commented on DeviceServices/canbus/commands/add_string_device.sh
> +    "profileName": "canbus-profile-strings",
added a note into the walkthrough section that to use the commands that include string update the profiles.json.

2024-01-22 15:55 UTC, Tylerg2471 commented on DeviceServices/canbus/commands/add_string_device.sh
> +    "profileName": "canbus-profile-strings",
The reason for having the two profiles is resources with string as the type aren't supported in the continuous read, so a seperate profile has examples for using strings and the same with the commands.

2024-01-23 15:31 UTC, BinduRao2018 commented
@Tylerg2471, one outstanding comment -  canbus-profile-strings.json isn't checked in.

2024-01-23 15:39 UTC, BinduRao2018 requested changes

2024-01-23 15:39 UTC, BinduRao2018 commented on DeviceServices/canbus/commands/add_string_device.sh
> +    "profileName": "canbus-profile-strings",
@Tylerg2471, canbus-profile-strings.json isn't checked in.

2024-01-24 14:06 UTC, Tylerg2471 commented
> @Tylerg2471, one outstanding comment - canbus-profile-strings.json isn't checked in. Also, it makes sense to add the hardware configuration that was used to test the DS.

Fixed now uploaded the profile

2024-01-24 15:44 UTC, BinduRao2018 approved these changes
LGTM

2024-01-24 15:44 UTC, merged