XRT-2585: Updated canbus v3.0 examples
IOTechSystems/xrt-examples pull request #269
Opened 2024-02-05 09:50 UTC by Tylerg2471

2024-04-16 09:34 UTC, BinduRao2018 reviewed
@Tylerg2471, one minor comment

2024-04-16 09:34 UTC, BinduRao2018 commented on DeviceServices/canbus/deployment/config/2-logger.json
> +  "Level":"Trace"
Should this be 'Warn'?

2024-04-16 12:23 UTC, SteveOss commented on DeviceServices/canbus/deployment/config/2-logger.json
> +  "Level":"Trace"
I would say the the default log level for all examples should perhaps info or warn. Thoughts ?

2024-04-16 12:30 UTC, Tylerg2471 commented on DeviceServices/canbus/deployment/config/2-logger.json
> +  "Level":"Trace"
Yeah Warn is what it normally is set to will fix.

2024-04-16 13:16 UTC, SteveOss requested changes

2024-04-16 13:16 UTC, SteveOss commented on DeviceServices/canbus/README.md
> +For more information about the Device Service please review the [CANbus Device Service](hhttps://docs.iotechsys.com/edge-xrt20/device-service-components/canbus-device-service-component.html) document
Should be a link to v3 not v2

2024-04-16 15:08 UTC, SteveOss requested changes
Does the link actually resolve to anything ?

2024-04-16 15:26 UTC, Tylerg2471 commented
> Does the link actually resolve to anything ?

No it doesn't, where are the 3.0 connect docs hosted?

2024-04-16 15:28 UTC, SteveOss commented
Look under: https://docs.iotechsys.com/edge-connect30/

2024-04-18 11:01 UTC, BinduRao2018 approved these changes
LGTM

2024-04-18 11:02 UTC, BinduRao2018 commented
@SteveOss, The 3.0 doc isn't hosted yet, but the links are now pointing to them. Is this is ok?

2024-06-25 12:18 UTC, BinduRao2018 commented
@SteveOss Is this good to go?

2024-06-25 12:20 UTC, SteveOss approved these changes
LGTM

2024-06-25 12:21 UTC, merged