XRT-2827: added canbus examples
IOTechSystems/xrt-examples pull request #277
Opened 2024-03-06 14:17 UTC by Tylerg2471

2024-03-07 15:48 UTC, BinduRao2018 requested changes

2024-03-07 15:48 UTC, BinduRao2018 commented on DeviceServices/canbus/README.md
> +For more information about the Device Service please review the [CANbus Device Service](https://docs.iotechsys.com/edge-xrt21/device-service-components/canbus-device-service-component.html)
pointing to Xrt:2.1 path (generic)

2024-03-07 15:48 UTC, BinduRao2018 commented on DeviceServices/canbus/README.md
> +. ./commands/set_env_vars.sh
set_env_var.sh is now at the top level instead of setting it at device service level

2024-03-07 15:48 UTC, BinduRao2018 commented on DeviceServices/canbus/commands/set_env_vars.sh
> +#!/bin/sh
This file is no longer required.

2024-03-12 13:44 UTC, Tylerg2471 commented on DeviceServices/canbus/README.md
> +. ./commands/set_env_vars.sh
Updated path

2024-03-12 13:44 UTC, Tylerg2471 commented on DeviceServices/canbus/commands/set_env_vars.sh
> +#!/bin/sh
Removed

2024-03-12 13:44 UTC, Tylerg2471 commented on DeviceServices/canbus/README.md
> +For more information about the Device Service please review the [CANbus Device Service](https://docs.iotechsys.com/edge-xrt21/device-service-components/canbus-device-service-component.html)
Fixed version

2024-03-12 14:40 UTC, BinduRao2018 commented on DeviceServices/canbus/README.md
> +For more information about the Device Service please review the [CANbus Device Service](https://docs.iotechsys.com/edge-xrt21/device-service-components/canbus-device-service-component.html)
@Tylerg2471, the setup still has reference to 2.1

2024-03-12 14:42 UTC, BinduRao2018 requested changes
Reference to 2.1 in README

2024-03-12 14:51 UTC, BinduRao2018 approved these changes

2024-03-12 14:51 UTC, merged