XRT-2842 feat: updates opc-ua sim scripts and add new one showing how to read/write
IOTechSystems/xrt-examples pull request #279
Opened 2024-03-13 09:48 UTC by Jwcode-uk

2024-03-13 11:02 UTC, Jwcode-uk commented
Was tempted to add instructions to set up a OPC-UA browser but we have that in like 3 different places in the examples dir so might be worth just making a folder under server/opc-ua covering it maybe? or could just link to the browser docs

2024-03-14 16:01 UTC, dpazj requested changes

2024-03-14 16:01 UTC, dpazj commented on Simulators/opc-ua/readWrite.lua
> +end
EOF newline

2024-03-14 16:01 UTC, dpazj commented on Simulators/opc-ua/readWrite.lua
> +  end
Not to big of a fan of all the (nested) if statements checking for `nil`  as it clutters up the function IMO. Are they all necessary for the scrip to work? If they are necessary group them together e.g
```lua
function Update()
  -- Attempt to get the current value of the counter node
  local counter_variant = Variant.new(DataType.DOUBLE)
  local counter_value_variant = counter_node:getValue()
  local sf_value_variant = sf_node:getValue()
  local counter_value
  if counter_value_variant == nil or sf_value_variant == nil then
    return
  end
 //update nodes

end

```

2024-03-15 08:58 UTC, Jwcode-uk commented on Simulators/opc-ua/readWrite.lua
> +  end
They are not required, just added them to ensure the variant is returned successfully

can remove

2024-03-15 09:01 UTC, Jwcode-uk commented on Simulators/opc-ua/readWrite.lua
> +  end
removed nil check

2024-03-15 11:25 UTC, dpazj approved these changes
LGTM

2024-03-18 13:31 UTC, dpazj approved these changes
LGTM

2024-03-18 13:33 UTC, merged