Xrt 2947: Add XRT Library Example
IOTechSystems/xrt-examples pull request #292
Opened 2024-06-11 14:30 UTC by Jwcode-uk

2024-06-13 14:35 UTC, Tylerg2471 requested changes
Few things to look at

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/readme.md
> +
* Rename readme.md to README.md
* Need to add in where/how to install required packages (Link to docs would be best)
* Add a link to API docs for Xrt as a library

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +struct bus_component_t
typedef this

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +  struct sigaction signal_action = {0};
Need a null check for config_uri?

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +      	if (wait_for_reply(100))
Why hardcoded 100? Could be a define

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +	      sleep(5);
Should we be using a sleep? If so would be better to define the value rather than magic number

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +  return 0;
Should this always return 0? Could return other value for error

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +      iot_log_info (bus->logger, "did not receive reply");
Think messages like this should be iot_log_error or warn rather than info.

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +#include <signal.h>
Couple things not line specific:
* Does the c and cpp files need copyright at the top?
* Formatting needs fixed (to coding standards) 
* Not checking return values of functions that have return values

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.c
> +  memset (&signal_action, 0, sizeof (signal_action));
Don't need to memset as initialising to 0

2024-06-13 14:35 UTC, Tylerg2471 commented on Library/demo.cpp
> +#include <signal.h>
Comments in .c file may carry over

2024-06-13 14:48 UTC, JonathanWhiteUK commented on Library/demo.c
> +      	if (wait_for_reply(100))
Done in C

2024-06-13 14:49 UTC, Jwcode-uk commented on Library/demo.c
> +  struct sigaction signal_action = {0};
Done in C

2024-06-13 14:49 UTC, Jwcode-uk commented on Library/demo.c
> +	      sleep(5);
Done in C

2024-06-13 14:50 UTC, Jwcode-uk commented on Library/demo.c
> +      iot_log_info (bus->logger, "did not receive reply");
Done in C

2024-06-13 14:50 UTC, Jwcode-uk commented on Library/demo.c
> +struct bus_component_t
Done in C

2024-06-17 14:14 UTC, JonathanWhiteUK commented on Library/demo.c
> +  struct sigaction signal_action = {0};
Fixed in C++

2024-06-17 14:14 UTC, Jwcode-uk commented on Library/demo.c
> +      	if (wait_for_reply(100))
Fixed in C++

2024-06-17 14:14 UTC, Jwcode-uk commented on Library/demo.c
> +	      sleep(5);
Fixed in C++

2024-06-17 14:15 UTC, Jwcode-uk commented on Library/demo.c
> +      iot_log_info (bus->logger, "did not receive reply");
Done in C++

2024-06-25 11:15 UTC, Tylerg2471 approved these changes
lgtm

2024-06-25 12:12 UTC, BinduRao2018 commented
- Update 'README' at the top level

2024-06-25 13:40 UTC, merged