XRT-3133: opc ua server configs update
IOTechSystems/xrt-examples pull request #309
Opened 2024-10-30 17:34 UTC by BinduRao2018

2024-11-05 17:01 UTC, BinduRao2018 commented
@dpazj Simplified example configs as discussed. Tests on CI:https://jenkins.iotechsys.com/view/Components/job/XRT/job/XRT-3133-branch/42/console

Ready for re-review

2024-11-07 14:48 UTC, dpazj requested changes
Minor comments

2024-11-07 14:48 UTC, dpazj commented on Servers/opc-ua/basic/README.md
> +Refer [Generate Certificates][1] to generate and update `ApplicationUri`, `Certificate` and `PrivateKey` in `config/opc-ua-server-securitypolicy.json`.
Refer to

2024-11-07 14:48 UTC, dpazj commented on Servers/opc-ua/basic/README.md
> +Refer [Generate Certificates][1] to generate and Update `ApplicationUri`, `Certificate` and `PrivateKey` in `config/opc-ua-server-x509cert.json`.
Refer to

2024-11-07 14:48 UTC, dpazj commented on Servers/opc-ua/basic/deployment/config/opc-ua-server-securitypolicy.json
> +    }
Is it worth changing this to 
```suggestion
{
     "SecurityPolicy": "None",
     "DiscoveryOnly" : true
}
```
So that with a client they can only connect with security policy enabled

2024-11-08 16:24 UTC, BinduRao2018 commented on Servers/opc-ua/basic/deployment/config/opc-ua-server-securitypolicy.json
> +    }
@dpazj, 'DiscoveryOnly" option is added only in 2.3 and not in 2.2

2024-11-12 12:09 UTC, BinduRao2018 commented on Servers/opc-ua/basic/deployment/config/opc-ua-server-securitypolicy.json
> +    }
updated

2024-11-18 16:18 UTC, dpazj approved these changes
LGTM

2024-11-19 09:50 UTC, merged