XRT-1056: Added interactive example walk through and added opc-ua walkthrough scripts
IOTechSystems/xrt-examples pull request #54
Opened 2021-11-15 13:58 UTC by dpazj

2021-11-15 16:11 UTC, FraserG01 requested changes
Looking good, I have added a few comments

One extra here:
- Is it worth mentioning the topic names we are writing to / getting replies on during the walkthrough

ie. when we are under the **Reading** heading, could it be worth explaining that we will be making a request on the _RequestTopic_ and will be receiving a response from the _ReplyTopic_

Under the **Schedule Management** explain that we will be writing to the _ScheduleRequestTopic_, receive a reply it was successful on the _ScheduleReplyTopic_ and receive data on the _Topic_

2021-11-15 16:11 UTC, FraserG01 commented on DeviceServices/opc-ua/commands/add_discovered_device.sh
> +}'
newline

2021-11-15 16:11 UTC, FraserG01 commented on DeviceServices/opc-ua/commands/get_multi_request.sh
> +}'
new line

2021-11-15 16:11 UTC, FraserG01 commented on DeviceServices/opc-ua/commands/get_request.sh
> +}'
newline

2021-11-15 16:11 UTC, FraserG01 commented on DeviceServices/opc-ua/commands/put_multi_request.sh
> +}'
newline

2021-11-15 16:11 UTC, FraserG01 commented on DeviceServices/opc-ua/profiles/profiles.json
> +["opc-ua-sim-profile","LDS_profile"]
newline

2021-11-15 16:11 UTC, FraserG01 commented on DeviceServices/opc-ua/state/schedules.json
> +{"schedule1":{"device":"opc-ua-sim-device","resource":["Counter"],"interval":3000000,"name":"schedule1"}}
newline

2021-11-16 10:38 UTC, FraserG01 requested changes

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/opc-ua/README.md
> +### **Common device service setup**
Can you capitalise the whole title

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/opc-ua/README.md
> +**Follow [Device Service Example Getting Started](../interactive-walkthrough/ds-getting-started-common.md) for the common device service example setup steps.**
Dont think you need to bold the whole thing

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/ds-getting-started-common.md
> +## Device service configuration setup
Capitalise all of title

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/ds-getting-started-common.md
> +## XRT MQTT Bridge configuration
Maybe worth mentioning in this section that the device service set_env_vars.sh script will already set these for you

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/ds-getting-started-common.md
> +## Device service configuration setup
Also maybe worth mentioning in this section that the device service set_env_vars.sh script will already set these for you

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/ds-getting-started-common.md
> +### Setup MQTT Broker
Should this title not be a level higher so its on the same level as XRT MQTT Bridge configuration

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/basic-operations.md
> +Device management requests will be made on the `RequestTopic` and will be received on the `ReplyTopic`, as set in the device service configuration file.
Say what will be received on the reply topic, success indication etc

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/basic-operations.md
> +Reading requests will be made on the `RequestTopic` and will be received on the `ReplyTopic`, as set in the device service configuration file.
Explain readings will be returned or indication the reading failed

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/basic-operations.md
> +Writing requests will be made on the `RequestTopic` and will be received on the `ReplyTopic`, as set in the device service configuration file.
Explain on reply it will indicate whether it was successful or not

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/basic-operations.md
> +Schedule requests will be made on the `ScheduleRequestTopic` and will be received on the `ScheduleReplyTopic`, as set in the device service configuration file.
on reply we are told if it was successful or not

The data from the schedule is then received on the topic: Topic

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/opc-ua/README.md
> +We can setup a subscription to a monitored resource using auto events. This will produce a reading every time the value we have subscribed to changes.
missing topic descriptions here

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/discovery.md
> +Discovery requests will be made on the `DiscoveryRequestTopic`, a reply if the request is successful or not will be received on the `DiscoveryReplyTopic`, and a list of discovered devices will be rec
These values can be seen and set in the device service configuration file.

to 

The names of these topics can be seen and set in the device service configuration file.

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/discovery.md
> +On the xrt reply topic we have subscribed to, we should see information and protocol properties about devices that have been discovered.
I would just take this line out as you explain in the paragraph above

2021-11-16 10:38 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/discovery.md
> +./remove_device_profile.sh
worth mentioning the profile topics?

2021-11-16 11:25 UTC, dpazj commented on DeviceServices/interactive-walkthrough/discovery.md
> +./remove_device_profile.sh
Cant hurt

2021-11-16 11:45 UTC, FraserG01 commented on DeviceServices/opc-ua/README.md
> +We can setup a subscription to a monitored resource using auto events. This will produce a reading every time the value we have subscribed to changes.
still missing topic descriptions

2021-11-16 11:47 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/discovery.md
> +./remove_device_profile.sh
...set in the device service **configuratin** file.

typo

2021-11-16 11:49 UTC, dpazj commented on DeviceServices/opc-ua/README.md
> +We can setup a subscription to a monitored resource using auto events. This will produce a reading every time the value we have subscribed to changes.
I added a link to topic descriptions here: https://github.com/IOTechSystems/xrt-examples/pull/54/commits/9a4b13a190d832234e41957544eed20c12e5e56e#diff-4bf636158911a68d1973edb5d8868b649cd3f38a025aa111fecabbf4857e17deR67

2021-11-16 13:31 UTC, FraserG01 approved these changes
LGTM

2021-11-16 13:53 UTC, amaan-akram approved these changes
LGTM

2021-11-16 14:05 UTC, amaan-akram commented
Not directly related but -

Should we add links to the examples from the root of the readme e.g. https://github.com/IOTechSystems/xrt-examples/blob/v1.2-branch/README.md this readme (at the bottom) would have a link to  https://github.com/IOTechSystems/xrt-examples/tree/v1.2-branch/DeviceServices and a readme from within the DeviceServices dir  would have links to the individual device service examples e.g. OPC-UA

May make it easier to navigate

2021-11-16 14:53 UTC, FraserG01 commented
> Not directly related but -
> 
> Should we add links to the examples from the root of the readme e.g. https://github.com/IOTechSystems/xrt-examples/blob/v1.2-branch/README.md this readme (at the bottom) would have a link to https://github.com/IOTechSystems/xrt-examples/tree/v1.2-branch/DeviceServices and a readme from within the DeviceServices dir would have links to the individual device service examples e.g. OPC-UA
> 
> May make it easier to navigate

@amaan-akram I agree with that

2021-11-16 14:59 UTC, PMacald reviewed
Just one small typo, I agree with the rest + Fraser's adjustments, LGTM.

2021-11-16 14:59 UTC, PMacald commented on DeviceServices/interactive-walkthrough/discovery.md
> +We can trigger discovery to recieve information about available devices.
Slight typo with receive here

2021-11-16 15:12 UTC, PMacald approved these changes
LGTM

2021-11-16 15:17 UTC, amaan-akram requested changes

2021-11-16 15:17 UTC, amaan-akram commented on DeviceServices/README.md
> +* [Virtual](DeviceServices/virtual)
broken links - remove 'DeviceServices'

2021-11-16 15:22 UTC, dpazj commented on DeviceServices/README.md
> +* [Virtual](DeviceServices/virtual)
fixed :)

2021-11-16 15:23 UTC, amaan-akram approved these changes

2021-11-16 15:26 UTC, FraserG01 approved these changes

2021-11-25 11:25 UTC, amaan-akram commented on DeviceServices/opc-ua/commands/add_device.sh
> +  "profile": "opc-ua-sim-profile",
"profile" needs to be moved into "device_info"? https://iotechsys.atlassian.net/wiki/spaces/EN/pages/2232877441/Edge+XRT+MQTT+Management+API#Add-Device

2021-12-02 12:26 UTC, FraserG01 requested changes

2021-12-02 12:26 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/basic-operations.md
> +cd ~/xrt-examples/DeviceServices/opc-ua/commands
can we take this up a level to /xrt-examples/DeviceServices/opc-ua

2021-12-02 12:26 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/basic-operations.md
> +./remove_device.sh
can we change all of these commands to 

./commands/remove_device.sh

2021-12-02 12:26 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/discovery.md
> +* Your present working directory is your chosen device service's commands folder e.g:
Your present working directory is your chosen device service example folder e.g:

2021-12-02 12:26 UTC, FraserG01 commented on DeviceServices/interactive-walkthrough/discovery.md
> +cd ~/xrt-examples/DeviceServices/opc-ua/commands
can we bring this up a level to:

cd ~/xrt-examples/DeviceServices/opc-ua

2021-12-02 12:26 UTC, FraserG01 commented on DeviceServices/opc-ua/README.md
> +./add_subscription.sh
./commands/add_subscription.sh

2021-12-02 12:26 UTC, FraserG01 commented on DeviceServices/opc-ua/commands/set_env_vars.sh
> +export XRT_PROFILE_DIR=$SCRIPT_DIR/../profiles/
export XRT_PROFILE_DIR=$PWD/profiles/

2021-12-02 12:37 UTC, FraserG01 commented on DeviceServices/opc-ua/commands/add_discovered_device.sh
> +mosquitto_pub -t xrt/device/opc_ua_device_service/request -m \
some of your scripts have #!/bin/sh at the top and others dont, can you add it to all of them

2021-12-06 09:22 UTC, dpazj commented on DeviceServices/opc-ua/config/logger.json
> +  "Level":"Warn"
Spoke with Bindu about this, and we should have this on Warn for when customers use it.

2021-12-06 09:27 UTC, dpazj commented on DeviceServices/opc-ua/commands/set_env_vars.sh
> +export XRT_PROFILE_DIR=$SCRIPT_DIR/../profiles/
Having the environment variable like this means that the user can execute the script from anywhere though - as long as the folder structure is set up appropriately the script will work. If we use $PWD then the user has to be in the correct directory so there are more things that could go wrong.

2021-12-06 10:59 UTC, FraserG01 approved these changes
LGTM

2021-12-06 12:04 UTC, Tylerg2471 commented
LGTM

2021-12-06 12:05 UTC, merged